#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
cd ./samples/tabcmd/
version=`cat VERSION`
echo "version: $version"
docker build -t tuatan/unofficial-tableau-tabcmd .
echo "version: $version"
docker push tuatan/unofficial-tableau-tabcmd:$version
